### ISSUE TITLE
Crash when loading system. 

### ISSUE THREAD

**Issue by cbaggers** [lispgames/cl-sdl2#85] opened 2017-03-15 09:56 UTC
This has started since the latest quicklisp release `cl-sdl2-20170227-git`

```TEST-OPTIMA> (ql:quickload :sdl2)
To load "sdl2":
  Install 1 Quicklisp release:
    cl-sdl2
; Loading "sdl2"
..................................................
[package sdl2-ffi]................................
[package sdl2-ffi.accessors]......................
[package sdl2-ffi.functions]......................
[package sdl2]....................................
[package sdl2-examples]...........................
..................................................
..................................................
.....................................

; file: /Users/Baggers/quicklisp/dists/quicklisp/software/cl-sdl2-20170227-git/src/syswm.lisp
; in: DEFUN GET-WINDOW-WM-INFO
;     (SDL2::INFO :INFO :WIN :WINDOW)
; ==>
;   (PLUS-C:C-REF #:TMP0 SDL2-FFI:SDL-SYSWM-INFO :INFO :WIN :WINDOW)
; 
; caught ERROR:
;   during macroexpansion of (C-REF #:TMP0 SDL2-FFI:SDL-SYSWM-INFO ...). Use
;   *BREAK-ON-SIGNALS* to intercept.
;   
;    Unknown field :WINDOW for foreign-record type:
;   #<AUTOWRAP:FOREIGN-RECORD ANON-TYPE-993 {100482A323}>
;   Valid fields:
;     :HDC (SDL2-FFI:HDC)
;   
```
Error:
```
COMPILE-FILE-ERROR while
compiling #<CL-SOURCE-FILE "sdl2" "syswm">
   [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]

Restarts:
 0: [RETRY] Retry compiling #<CL-SOURCE-FILE "sdl2" "syswm">.
 1: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "sdl2" "syswm"> as having been successful.
 2: [RETRY] Retry ASDF operation.
 3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 4: [ABORT] Give up on "sdl2"
 5: [*ABORT] Return to SLIME's top level.
 --more--

Backtrace:
  0: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2" "syswm">)))
      Locals:
        CONTEXT-ARGUMENTS = ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2" "syswm">))
        CONTEXT-FORMAT = "~/asdf-action::format-action/"
        FAILURE-P = T
        OUTPUT = NIL
        WARNINGS-P = T
  1: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2" "syswm">)
      Locals:
        SB-DEBUG::ARG-2 = #<ASDF/LISP-ACTION:COMPILE-OP >
        SB-DEBUG::ARG-3 = #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2" "syswm">
```

**Comment by cbaggers** [comment] 2017-03-15 10:01
It's pretty disappointing to see bugs like this in quicklisp as it means it will be another month until we can get the fix to most people. 

It would be ace if we could set up Travis & AppVeyor accounts to simply run `asdf:load-system` with :verbose & :force on every commit. That would at least catch this class of errors. I'm happy to set up the config files for this if you folks like this idea

**Comment by rpav** [comment] 2017-03-15 13:50
Hrm I can't reproduce this with either autowrap on master or libffi branches .. also made sure cl-sdl2 was latest, nuked fasls, etc.  You don't happen to have an old autowrap hanging around somewhere perchance?

WRT Travis etc .. go for it!  I'm not sure how all the fancy stuff works but anything to help catch errors on commits/PRs would be neat.

**Comment by cbaggers** [comment] 2017-03-15 14:57
Summary from IRC Chat:

- Baggers is using autowrap from quicklisp
- Problem is due to current testing being linux only (we are looking into CI solutions now)
- Became problem in quicklisp after: https://github.com/lispgames/cl-sdl2/commit/1c24e9c1282b5869795e66fdf7bd035d9754dcb2
- works on linux because the struct likely has all the fields there, but not on other OS's
- Possible HDC linux issue?
- currently has define a bunch of basic windows types in SDL2.h and force it to think it's also windows

**Comment by rpav** [comment] 2017-03-15 15:03
Specifically, on Linux I define a bunch of basic Windows types so `c2ffi` can generate Windows specs on Linux or other platforms.  So most Windows structs also work, but other platforms don't work on Windows.

The fix is just to prevent platform-specific stuff from compiling everwhere with trivial-features.  Should probably also make a specific `.h` for Windows-only stuff, but that'll require tweaking in a number of places (i.e. autowrap `c-include` to take different headers per platform).

**Comment by ajpaon** [comment] 2017-05-27 01:47
I'm running into this issue on Mac OS. Is there a workaround?

**Comment by rpav** [comment] 2017-05-27 02:21
This should surely have been fixed in the latest QL.  Try updating your dist, and/or any repositories you have manually checked out.

**Comment by ajpaon** [comment] 2017-05-28 02:23
Ah, that did it. Thank you! Sorry for the noise

**Closed** 2017-11-02 22:16 UTC
