### ISSUE TITLE
Installation instructions won't work for CLISP

### ISSUE THREAD

**Issue by tjohnman** [lispgames/cl-sdl2#44] opened 2015-09-02 17:11 UTC
Following the installation instructions in the README will end up in this:

``` lisp
[2]> (asdf:load-system :sdl2-examples)
;; Compiling file /home/*****/quicklisp/local-projects/cl-sdl2/examples/basic.lisp ...
*** - LOAD: A file with name SDL2 does not exist
The following restarts are available:
RETRY          :R1      Retry compiling #<CL-SOURCE-FILE "sdl2-examples" "basic">.
ACCEPT         :R2      Continue, treating compiling #<CL-SOURCE-FILE "sdl2-examples" "basic"> as having been successful.
ABORT          :R3      Abort main loop
```

**Comment by rpav** [comment] 2015-09-02 17:25
Hmm, this appears to be CLISP, which is known to have issues.  Unfortunately I've had issues building a CLISP with all the necessary features to support this so testing has been limited.

With CCL and SBCL, I can't reproduce this, though.

**Comment by tjohnman** [comment] 2015-09-03 13:58
SBCL works. Thanks for the heads up.

**Comment by ryukinix** [comment] 2016-02-28 08:21
CLISP really don't works with that, same issue here. CLISP are outdated.

**Comment by mfiano** [comment] 2017-11-20 23:55
This won't be fixed, as CLISP is both unmaintained and does not have the performance required for most uses of SDL2 applications.

**Closed by mfiano** 2017-11-20 23:55 UTC

**Comment by lstyrtmrnbd** [comment] 2018-03-01 16:47
I wish this was mentioned somewhere up-front
