### ISSUE TITLE
basic-examples doesn't run on SBCL/OS X, bogus stack frame?

### ISSUE THREAD

**Issue by ysgard** [lispgames/cl-sdl2#29] opened 2014-10-04 19:40 UTC
I open sbcl and run:

(asdf:load-system :sdl2)
(asdf:load-system :sdl2-examples)

They load fine (albeit with a couple of warnings).    

But when I run:

(sdl2-examples::basic-test)

The window pops up with the red rectangle, but the menu bar doesn't resolve (no minimize/maximize buttons), the example is nonresponsive and the mouse just shows the spinning ball inside of it.  I cannot kill it and have to issue a ^C in the terminal.
In the terminal after the ^C I see:
- (sdl2-examples::basic-test)
  Using SDL Library Version: 2.0.3
  Setting up window/gl.
  Opening game controllers.
  Beginning main loop.
  ^C
  debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
  #<THREAD "main thread" RUNNING {1002C0E803}>:
  Interactive interrupt at #x7FFF9C1CD486.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Return from SB-UNIX:SIGINT.
  1: [ABORT   ] Exit debugger, returning to top level.

("bogus stack frame")
0]

**Comment by capitaomorte** [comment] 2015-02-16 20:11
HI @rpav, I just bumped into this issue myself and none of the two sbcl workarounds you posted on Dec 18 work. CCL is fine for experiments, and I can always VM to linux I guess, but can you give me a bit more context about the sbcl fail? Is there a sbcl ticket for this, or is it not its fault?

**Comment by rpav** [comment] 2015-02-16 20:15
This isn't *really* an SBCL issue, beyond "SBCL can't safely interrupt a thread," which I doubt will be fixed soon.

Can you gist the code you tried that doesn't work?  Note I haven't tried this on Yosemite, since my only OSX box is an aging iMac that doesn't even get along terribly well with Mavericks.

**Comment by capitaomorte** [comment] 2015-02-16 20:36
I still use Mavericks too:

```
$ sbcl
* (load "~/path/to/sly/slynk/slynk-loader.lisp")
* (slynk:init)
* (slynk-create-server :port 4005)
* (sdl2:make-this-thread-main (lambda () (sdl2:init :everything))
```
Alright, this blocks the REPL as you warned beforehand, but it's apparently still good for output as in Emacs. Indeed, if I put

```
M-x sly-connect RET 4005 RET
```

it connects, giving me a REPL. Now I try 

```
CL-USER> (ql:quickload :sdl2-examples)
CL-USER> (sdl2-examples:basic-test)
```

But the problem is exactly the same as originally reported: wait a bit then spinning pizza. I'm using SLY, but the very same thing happens with SLIME, btw.

**Comment by capitaomorte** [comment] 2015-02-16 20:39
A bit related: I'm on an ageing imac, too (2009 version)
Completely unrelated: before discovering `cl-sdl2`, I was going to try your `cl-autowrap` on `sfml`. Any obvious reason why you didn't try that, too?

**Comment by rpav** [comment] 2015-02-16 20:44
Yeah, that won't work: `sdl2-examples:basic-test` is using "raw" SDL2, and does its own `init` etc.  I *think* you should be able to do:

```lisp
(sdl2:make-this-thread-main (lambda () (sdl2-examples:basic-test)))
```

I would recommend using `sdl2kit`:

```lisp
(sdl2:make-this-thread-main #'kit.sdl2:start)
```

...which should start sdl2kit's main loop and let you make and manage windows through that.  In this case, you can't run `sdl2-examples:basic-test`, but the sdl2kit/glkit examples *should* work.

**Comment by rpav** [comment] 2015-02-16 20:53
Yeah.. I've never heard of SFML before!  I'm not sure why it wouldn't otherwise work (at least, as long as you bind CSFML).  I'm not sure what it offers over SDL2; at a glance it appears to offer a few more high-level things beyond what "plain" SDL2 has, but I'm not sure they're worth it alone.

I *don't* see controller support (at least in CSFML), which would be a pretty huge missing piece, if nothing else.

**Comment by capitaomorte** [comment] 2015-02-16 21:19
OK, I see. `sdl2kit` it is. You should link to it, Not obvious that it's its own repo and project. At least pre-google :-). 

And good to hear an opinion about SFML of someone with more SDL experience than me. The reason you focus on CSFML is because `cl-autowrap` will only wrap C bindings right? No `hpp`, right? Don't even know how that would work CFFI-wise...

**Comment by rpav** [comment] 2015-02-16 21:25
Yes... more or less nothing can wrap C++ yet.  In theory you could use [Clasp](https://github.com/drmeister/clasp), but I'm not sure what the state of that is.  SWIG can do some kind of basic generation, but I'm not sure about the state of that either---its C generator was poor enough I dropped it and made autowrap.

[c2ffi](https://github.com/rpav/c2ffi) now dumps a fair bit of C++, and in theory one could use that to generate C->C++ bindings, but I haven't gotten around to finishing that bit yet.  (It should actually be pretty straightforward.)

And yeah, we should really get the wiki here set up to make all the projects obvious...

**Closed** 2018-06-14 14:34 UTC
Labels: osx
